### ISSUE TITLE
add review and lv2 for linux

### ISSUE THREAD

**Issue by p-k-l** [Chowdhury-DSP/ChowMatrix#1]

**Comment by jatinchowdhury18** [comment]
Hi @p-k-l,

Not exactly sure what you mean by "add review"?

I'm working on generating LV2 builds... In the past I've used the DISTRHO fork of JUCE, but they don't yet support the JUCE6/CMake build process that I'm using for this plugin, so it may take a little time. I'll be sure to update this thread when I've got somethin ready to try out.

Thanks,
Jatin

**Comment by p-k-l** [comment]
Hi @jatinchowdhury18 
add a video review 
Thanks for reply 
best

**Comment by jatinchowdhury18** [comment]
Okay, I've got a build process set up for LV2 with CMake! To give it a try, just check out the [`lv2`](https://github.com/Chowdhury-DSP/ChowMatrix/tree/lv2) branch, and builds using CMake as described in the README. Please let me know if this works for you!

Tagging some folks who have helped me with testing in the past:
@KottV, @mxmilkiib

I'm hoping to make a video demo sometime in the next couple weeks (unfortunately, I'm very slow at making videos).

Thanks,
Jatin

**Comment by jatinchowdhury18** [comment]
Video demo is now live on YouTube: https://youtu.be/1mt5DaT_akE
