### ISSUE TITLE
[BUG] Adding nodes to the 'core' has the behaviour of adding node to the 1st node. 

### ISSUE THREAD

**Issue by Ble3azy** [Chowdhury-DSP/ChowMatrix#10]
**Describe the bug**
If I start with a 1/4 note node and then an 1/8 note node ( to the core, not on top the 1/4) it will sound as a 1/4 and a dotted 1/4, not an 1/8 and and 1/4. 
So it appears all nodes added after the first even if not added TO the first, behave as if they are added post first node. If would be nice to add initial nodes to the 'core' as independent starts. 

**Expected behavior**
If I add a node that isn't connected to another I expect to hear that delay interval, not the interval plus the first node that it isn't connected to.

**Desktop (please complete the following information):**
 - Windows 10 (19041)
 - Ableton Live 10.1
 - 64 bit Vst2 version

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this! Just to make sure I'm understanding this correctly, you're talking about a setting with two nodes, one with a 1/4 note delay, and one at with an 1/8 note delay. In your scenario, I understand the two delay nodes are in this configuration:
![image](https://user-images.githubusercontent.com/13724188/101726814-164bac80-3a68-11eb-8611-1a1f40d1d494.png)

not this one:
![image](https://user-images.githubusercontent.com/13724188/101726856-2bc0d680-3a68-11eb-9c2a-f2f3654d8018.png)

or this one:
![image](https://user-images.githubusercontent.com/13724188/101726884-3d09e300-3a68-11eb-8f69-89ca2ff156ad.png)

Is that correct? Just making sure I've got it right.

Thanks,
Jatin

**Comment by Ble3azy** [comment]
Yes that's correct. the top/first example.

timing wise, example 1 behaves as example 2.

Thanks for your time,
best of luck!
Ben
________________________________

**Comment by jatinchowdhury18** [comment]
Should be fixed now with 45f0cc6. I'll have some new builds to try out very soon!

**Comment by Ble3azy** [comment]
Fantastic thankyou.

I forgot to say congrats on the plugin in general well done.
________________________________

**Comment by jatinchowdhury18** [comment]
Thank you!

Finally got around to generating some new builds. Definitely let me know if these work correctly on your end: https://github.com/Chowdhury-DSP/ChowMatrix/tree/develop/bin

Thanks,
Jatin
