### ISSUE TITLE
Feature Request: add auto gain compensation

### ISSUE THREAD

**Issue by SamuelMiller** [Chowdhury-DSP/ChowMatrix#112]
Currently, it is difficult to compare dry/wet, A/B, or enabled/bypassed, because one has to manually match the gain. Please consider adding an optional auto gain compensation feature that would match the gain (e.g., RMS/LUF) regardless of what effect parameters are adjusted, besides the output gain which would override any auto gain matching. Thanks for offering such a great plugin for free.

**Comment by jatinchowdhury18** [comment]
Thanks for the suggestion! That's definitely a good idea. I'll have to take a look at how difficult it will be to implement, and hopefully I can include an auto-gain option in the next release!

**Comment by jatinchowdhury18** [comment]
Just implemented a version of automatic gain compensation, now on the develop branch. To switch it on, you can right-click on the "Wet" gain control, and turn it on from there. Right now, the auto-gain will make sure the wet signal is at the same level as the input signal _before_ the wet gain is applied. If you'd like to try it out, the feature should be in the next [nightly builds](https://chowdsp.com/nightly.html#matrix).

**Comment by SamuelMiller** [comment]
Awesome!
