### ISSUE TITLE
macOS installers require Rosetta

### ISSUE THREAD

**Issue by postprivee** [Chowdhury-DSP/ChowMatrix#139]
I've checked all official+nightly builds for each plugin and they all require Rosetta.

Any chance for native installers? Or should I use iOS versions for now?

**Comment by jatinchowdhury18** [comment]
Hi @postprivee,

Thanks for reporting this! The plugins themselves are all universal binaries, but you're correct that the installers are currently Intel binaries. I've tweaked the installer scripts for ChowMatrix to create a binary that should work cross-platform. If you're able to, would you mind trying out the next [nightly build](https://chowdsp.com/nightly.html#matrix) (should be ready in an hour or so)? If that works for you, then I can update our other plugins in the same way.

**Comment by postprivee** [comment]
@jatinchowdhury18 thanks Jatin! just got the nightly build for ChowMatrix + it works!

**Comment by jatinchowdhury18** [comment]
Awesome! I'll work on getting the installers for ChowTape and BYOD updated later today, so keep an eye on the nightly builds for those.
