### ISSUE TITLE
[BUG] Graph View resizing gets weird at large widths

### ISSUE THREAD

**Issue by jatinchowdhury18** [Chowdhury-DSP/ChowMatrix#57]
**Describe the bug**
At large widths the GraphView doesn't extend all the way to the end of the plugins window, and then when returning to a smaller width, the nodes are shifted too far to the right.

**To Reproduce**
1. Start at the default window size.
2. Resize the window to be very wide.
3. Resize the window back to a more normal width.

**Comment by tocan** [comment]
I use it in Davinci Resolve with Unify. If you are interest its my patch from Spitfire Labs Libary and its Frozen the GUI. Tell it John. Maybe an Update helps. I use the Version that is inside Unify 1.4
No standallone use of Matrix

It can cause because a bug of the spitfire VST.
