### ISSUE TITLE
[BUG]Linux standalone version has zero-size GUI.

### ISSUE THREAD

**Issue by KottV** [Chowdhury-DSP/ChowMatrix#78]
**Describe the bug**
ChowMatrix built from sources.
Running standalone version displays tiny window with close cross and resize triangle. Dragging by triangle allows resize of window, but after that when drag the window by header - window is collapsed to zero-size again.

**To Reproduce**
1. Build ChowMatrix for linux. I used both JUCE-6.0.8 and develop branch.
2. Run standalone version.

**Expected behavior**
Window should be normal size.

**Screenshots**
![Screenshot_20210415_150107](https://user-images.githubusercontent.com/4686351/114816527-a70e0c80-9dfb-11eb-9856-c4d9e1e4cd57.png)

**Desktop (please complete the following information):**
 - OS: openSUSE TW JUCE-6.0.8
 - DAW standalone version
 - Version [e.g. 2.3]
 - 32/64 bit (Windows only)

**Additional context**
It afect ChowPhaser too. But ChowTape, KlonCentaur displays fine.

**Comment by jatinchowdhury18** [comment]
Hi Konstantin,

Thanks for reporting this! I actually noticed something like this when I was trying to upgrade the JUCE submodule used by this repo. It looks lik something changed from JUCE version 6.0.7 to 6.0.8 that causes this issue. I was able to fix the issue with [this commit](https://github.com/Chowdhury-DSP/ChowMatrix/pull/79/commits/3db6711e0b284a6c57da073ca629f17f2a74b716).

Could you confirm that this fixes the issue with your build also? It's probably best to pull from [this branch](https://github.com/Chowdhury-DSP/ChowMatrix/pull/79).

Thanks,
Jatin

**Comment by KottV** [comment]
Hi Jatin,

Yes it fixed, thank You!

**Comment by jatinchowdhury18** [comment]
Awesome, great to hear it!
