### ISSUE TITLE
audio distorted in Logic 10.5.1

### ISSUE THREAD

**Issue by funkyrod99** [Chowdhury-DSP/ChowMatrix#9]
**Describe the bug**
audio is distorted in Logic 10.5.1
works fine in Ableton and is awesome!!

**Expected behavior**
works perfectly in Ableton

**Desktop (please complete the following information):**
 - OS: [MacOS 10.14.6]
 - DAW [e.g. Logic]
 - Version [10.5.1]

Works great in Ableton -- very creative and cool plugin -- thanks for this!

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this! I'll take a deeper look at this bug over the weekend. In the meantime, would it be possible to record a little bit of this distortion, and save a preset for the settings where the distortion occurs? That will help me with debugging.

Thanks,
Jatin

**Comment by funkyrod99** [comment]
Hi Jatin

Thanks for the fast reply!

Here’s an mp3 of the distortion — it sounds like a mismatch in the sample rates…?
input source is the factory electric piano plugin in Logic - default setting.
The ChowMatrix preset is the factory preset  “Lush”
I’ve tried switching the Logic session from 44 to 48 with no change.




cheers,

rodney

**Comment by jatinchowdhury18** [comment]
HI Rodney,

Thanks for the update. It looks like it was an issue with the way I was handling internal buffers. Would you mind giving these new builds a try: https://github.com/Chowdhury-DSP/ChowMatrix/tree/develop/bin

Thanks,
Jatin

**Comment by funkyrod99** [comment]
Hi Jatin,

Just checked it out, and it now works perfect in Logic!!  However, it did give a message when I first launched it asking if I wanted to download version 1.0.0.  Since I know this new one is 1.0.1, I declined.  I then quit Logic and tried the new version in Ableton and it still works perfectly there — both AU and VST.  Ableton did not ask about downloading version 1.0.0.
I launched logic again, and it now does not ask about downloading version 1.0.0.

It has already inspired me to write a cool chord progression!

Thanks Jatin!

I also have your modules for VCV rack, but haven’t got into them yet.  I’m going to explore them soon.

Cheers,

Rodney

**Comment by jatinchowdhury18** [comment]
Awesome! Good to hear that the distorting audio is fixed.

Sorry, I should have warned you about the auto-updater asking you to update, but the fact that it didn't ask you to update again after you declined is the expected behaviour, so I'm glad to hear that's working.

Thanks,
Jatin
